name: signup_rest_login
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+1

environment:
  sdk: ">=3.2.5 <4.0.0"


dependencies:
  just_audio_cache: ^0.1.1
  uuid: ^3.0.4
  http: ^0.13.6
  camera: ^0.10.5+9
  path_provider: ^2.0.2
  audioplayers: ^6.0.0
  chewie: ^1.2.2
  file_picker: ^8.0.0+1
  microphone: ^0.1.0
  flutter_sound: ^8.1.4
  firebase_database: ^10.5.0
  awesome_dialog: ^3.2.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  firebase_storage: ^11.7.0
  video_player: ^2.1.12
  just_audio: ^0.9.37
  flutter_screenutil: ^5.9.0
  flutter_offline: ^3.0.1
  flutter_downloader: ^1.6.1
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  google_sign_in: ^6.2.1
  rive: ^0.12.4
  youtube_player_flutter: ^9.0.0
  image_picker: ^0.8.4+2
  permission_handler: ^8.1.6
  dio: ^4.0.2
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets: