// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbt0s_xffzBTxcSsJIMaXj8pl9XOqOiYg',
    appId: '1:377946432959:web:7c8e56f5b2b9a318f32d0a',
    messagingSenderId: '862895588901',
    projectId: 'mobileappyoussefshahen',
    authDomain: 'deepfake-c64a9.firebaseapp.com',
    storageBucket: 'gs://mobileappyoussefshahen.appspot.com',
    measurementId: 'G-9WVK4BEYS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbt0s_xffzBTxcSsJIMaXj8pl9XOqOiYg',
    appId: 'mobileappyoussefshahen',
    messagingSenderId: '862895588901',
    projectId: 'mobileappyoussefshahen',
    storageBucket: 'gs://mobileappyoussefshahen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbt0s_xffzBTxcSsJIMaXj8pl9XOqOiYg',
    appId: '1:377946432959:ios:35e81ba23b262565f32d0a',
    messagingSenderId: '862895588901',
    projectId: 'mobileappyoussefshahen',
    storageBucket: 'gs://mobileappyoussefshahen.appspot.com',
    iosClientId: '377946432959-4fenbasc0205lhpm44n8fkml28nikq4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.signupRestLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbt0s_xffzBTxcSsJIMaXj8pl9XOqOiYg',
    appId: '1:377946432959:ios:f37335a7fa85ec18f32d0a',
    messagingSenderId: '862895588901',
    projectId: 'mobileappyoussefshahen',
    storageBucket: 'gs://mobileappyoussefshahen.appspot.com',
    iosClientId: '377946432959-0ojvrese9obl57hkvv1f7ntq9vf22c7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.signupRestLogin.RunnerTests',
  );
}
